[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd apps/frontend && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd apps/frontend && npm run build"]

[start]
cmd = "cd apps/frontend && npm run preview"
